apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-app-database
  labels:
    app: contact-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact-app
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: contact-app
        tier: database
    spec:
      containers:
      - name: database
        image: postgresql/alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: database
          containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: user
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: database-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: database-volume
        persistentVolumeClaim:
          claimName: database-claim

