apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "./kube/app/database/data"
